// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CosplayDate.Domain.Entities;

public partial class EscrowTransaction
{
    public int Id { get; set; }
    public int BookingId { get; set; }
    public int PaymentId { get; set; }
    public int CustomerId { get; set; }
    public int CosplayerId { get; set; }
    public decimal Amount { get; set; }
    public string Status { get; set; } = null!; // "Held", "Released", "Refunded"
    public string TransactionCode { get; set; } = null!;
    public DateTime CreatedAt { get; set; }
    public DateTime? ReleasedAt { get; set; }
    public DateTime? RefundedAt { get; set; }

    // Navigation properties
    public virtual Booking Booking { get; set; } = null!;
    public virtual Payment Payment { get; set; } = null!;
    public virtual User Customer { get; set; } = null!;
    public virtual Cosplayer Cosplayer { get; set; } = null!;
}